### ISSUE TITLE
容器 run/start/stop 均耗費很長時間

### ISSUE THREAD

**Issue by BirkhoffLee** [v2ray/install#13]
原因未知，不知道有沒有人有一樣的問題？其他容器都不會有這個問題。

`docker info`：
```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 51
Server Version: 17.12.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.826GiB
Name: docker-asia-1
ID: NCTM:FH7Z:DXFQ:XINV:SX45:EVLG:N5GW:ABJG:DYP7:ROVD:APGF:GZ26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

`docker-compose.yml`：
```yaml
version: '3.1'

services:

  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ${V2RAY_PATH}:/etc/v2ray
    expose:
      - "xxx" # VMess ws
    ports:
      - "xxx:xxx" # ShadowSocks
      - "xxx:xxx" # VMess main inbound
      - "xxx-xxx:xxx-xxx" # VMess dynamic ports
    environment:
      # support http/websocket stuff when required
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${SSL_DOMAINS}
      LETSENCRYPT_EMAIL: ${SSL_EMAIL}

networks:
    default:
       external:
         name: ${NETWORK}
```

```
[birkhoff@docker-asia-1 v2ray]$ docker-compose up -d
Creating v2ray ...
Creating v2ray
<這邊會卡很久>
ERROR: for v2ray  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for v2ray  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
[birkhoff@docker-asia-1 v2ray]$ docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
cdd03e740225        v2ray/official                           "v2ray -config=/etc/…"   3 minutes ago       Created                                                        v2ray
[birkhoff@docker-asia-1 v2ray]$ docker start cdd03e740225
<卡很久>
^C
[birkhoff@docker-asia-1 v2ray]$ docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
cdd03e740225        v2ray/official                           "v2ray -config=/etc/…"   3 minutes ago       Created                                                        v2ray
```

`stop` 也是如此。
